dist: trusty

language: python
python:
  - 3.5

addons:
  postgresql: "9.6"

install:
  - sudo apt-get install -qq postgresql-server-dev-9.6 postgresql-9.6-pgtap
  - psql -c 'CREATE DATABASE dbtools_test;'
  - psql -d dbtools_test -c 'CREATE EXTENSION pgtap;'

before_script:
  - make -C pg_extensions/pg_address
  - sudo make -C pg_extensions/pg_address install

  - make -C pg_extensions/partitions
  - sudo make -C pg_extensions/partitions install

  - psql -d dbtools_test -c 'CREATE EXTENSION pg_address;'
  - (cd libs/pg_address && python setup.py install)
  - pip install nose

script:
  - make -C pg_extensions/pg_address test
  - make -C pg_extensions/partitions test
  - make -C libs/pg_address test
